#include"print.h"
#include"ncurses.h"
#include<iostream>
#include <unistd.h>
#define DELAY 50000
using namespace std;
void printRace(){
	printw("please select your race\n\n");
	printw("h: Human----- Humans were primarily a scattered and tribal people for several millennia, until the rising strength of the troll empire forced their strategic unification. \n\n");// initial HP: 140, Atk: 20, Def:20 
	printw("e: Elves-----The Elves are not subject to disease or physical aging, though they could be killed by violence or by wasting away and losing the will to live. They were otherwise essentially immortalinitial\n");// HP: 140, Atk: 30, Def:10
	printw("d: Dwarf-----Dwarves are an ancient race of robust humanoids who live beneath the snow-capped mountains \n\n");//initial HP: 100, Atk: 20, Def:30,gold is doubled in value
	printw("o: Orc-----. Orcs are no longer driven by dreams of conquest, they stand ready to destroy all who would challenge their sovereignty or their supremacyinitial\n\n");// HP: 180, Atk: 30, Def:25,gold is worth half value
}


void printLogo(){
clear();
printw("$$$$$$$$$$$$$$$$\"\"$o$o$o$o$o$oo$$\"\"$$$$$$$$$$$$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$$$$$$$$$\"\"o$$$$$$$$$$\"$\"$$$$$$$o$\"$$$$$$$$$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$$$$$$\"$o$$$$\"\"$oo $ \"\"      \"\"\"$$$oo\"$$$$$$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$$$$\"o$$$$\"   \"\"o  $oo o o       \"\"$$$o\"$$$$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$$\"o$$$\"       oo$$$$$$$$$$o        \"$$$o\"$$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$\"o$$$  $  o$$$$$$$$$$$$$$\"$$oo       \"$$$ $$$$\n");
refresh();
 usleep(DELAY);
printw("$$$\"$$$\"   \"$$$$$$$$$$$$$$$$o$o$$$\"        $$$o$$$\n");
refresh();
 usleep(DELAY);
printw("$$ $$$    o$$$$$$$$$$$$$$$$$$$$$$$$o o   o  \"$$o\"$\n");
refresh();
 usleep(DELAY);
printw("$\"$$$\"    o$$$$$$$$$\"$$$$$$\"\" \"$$$$$$\"$$$$$  $$$\"$\n");
refresh();
 usleep(DELAY);
printw("$o$$\"    o$$$$$$$$$$o\"\"$$$\"\"\"\"ooo\"$$$$$$$$\"   $$$\"\n");
refresh();
 usleep(DELAY);
printw("$o$$\"    o$$$$$$$$$$            \"\"oo\"$\"$o\"\"   $$$o\n");
refresh();
 usleep(DELAY);
printw("o$$$     o$$$$$$$$$$                \"\"\"\"\"$    o$$o\n");
refresh();
 usleep(DELAY);
printw("o$$$    o$$$$$$$$$$$$o                   \"o \"oo$$o\n");
refresh();
 usleep(DELAY);
printw("o$$$  oo$$$$$$$$$$$$$$$$ooooooo$$$$$oo    $\"$ \"$$o\n");
refresh();
 usleep(DELAY);
printw("o$$$\"  \"\"  $$$$$$$$$$$$$$$$$$$$$$$$$$$$o    \" $$$\n");
refresh();
 usleep(DELAY);
printw("$ $$$       \"$$$$$$$$$$$$$$$$$$$$$$$$$$$o    o$$\"$\n");
refresh();
 usleep(DELAY);
printw("$$\"$$o       \"$$$$$$$$$$$$$$$$$$$$$$$$$$$o   $$$o$\n");
refresh();
 usleep(DELAY);
printw("$$o$$$o       $$\"\"$$$$$$$$$$$$$$$$$$$$$$$o  $$$ $$\n");
refresh();
 usleep(DELAY);
printw("$$$o\"$$o    \"$\"\"  \"$\"\"$$$$$$$$$$$$$$$$$$$oo$$$\"$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$o\"$$$o        \"     $$$$$$$$$$$$$$$$$o$$\"o$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$$$o\"$$$o         oo$$$$$$$$$$$$$$$$$$$$\"o$$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$$$$$o\"$$$$ooooo$$$$$$$$$$$$$$$$$$$$$$\"o$$$$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$$$$$$$o\"\"$$$$$$$$$$$$$$$$$$$$$$$$$\"oo$$$$$$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$$$$$$$$$$o$\"\"$$$$$$$$$$$$$$$$$\"\"oo$$$$$$$$$$$$\n");
refresh();
 usleep(DELAY);
printw("$$$$$$$$$$$$$$$$$$o$o$\"$\"$\"$\"$oo$o$$$$$$$$$$$$$$$$\n");

refresh();
usleep(DELAY);
clear();
refresh();
usleep(DELAY);
clear();
 printw("$$$$$$$$$$$$$$$$\"\"$o$o$o$o$o$oo$$\"\"$$$$$$$$$$$$$$$\n");
printw("$$$$$$$$$$$$\"\"o$$$$$$$$$$\"$\"$$$$$$$o$\"$$$$$$$$$$$$\n");
printw("$$$$$$$$$\"$o$$$$\"\"$oo $ \"\"      \"\"\"$$$oo\"$$$$$$$$$\n");
printw("$$$$$$$\"o$$$$\"   \"\"o  $oo o o       \"\"$$$o\"$$$$$$$\n");
printw("$$$$$\"o$$$\"       oo$$$$$$$$$$o        \"$$$o\"$$$$$\n");
printw("$$$$\"o$$$  $  o$$$$$$$$$$$$$$\"$$oo       \"$$$ $$$$\n");
printw("$$$\"$$$\"   \"$$$$$$$$$$$$$$$$o$o$$$\"        $$$o$$$\n");
printw("$$ $$$    o$$$$$$$$$$$$$$$$$$$$$$$$o o   o  \"$$o\"$\n");
printw("$\"$$$\"    o$$$$$$$$$\"$$$$$$\"\" \"$$$$$$\"$$$$$  $$$\"$\n");
printw("$o$$\"    o$$$$$$$$$$o\"\"$$$\"\"\"\"ooo\"$$$$$$$$\"   $$$\"\n");
printw("$o$$\"    o$$$$$$$$$$            \"\"oo\"$\"$o\"\"   $$$o\n");
printw("o$$$     o$$$$$$$$$$                \"\"\"\"\"$    o$$o\n");
printw("o$$$    o$$$$$$$$$$$$o                   \"o \"oo$$o\n");
printw("o$$$  oo$$$$$$$$$$$$$$$$ooooooo$$$$$oo    $\"$ \"$$o\n");
printw("o$$$\"  \"\"  $$$$$$$$$$$$$$$$$$$$$$$$$$$$o    \" $$$\n");
printw("$ $$$       \"$$$$$$$$$$$$$$$$$$$$$$$$$$$o    o$$\"$\n");
printw("$$\"$$o       \"$$$$$$$$$$$$$$$$$$$$$$$$$$$o   $$$o$\n");
printw("$$o$$$o       $$\"\"$$$$$$$$$$$$$$$$$$$$$$$o  $$$ $$\n");
printw("$$$o\"$$o    \"$\"\"  \"$\"\"$$$$$$$$$$$$$$$$$$$oo$$$\"$$$\n");
printw("$$$$o\"$$$o        \"     $$$$$$$$$$$$$$$$$o$$\"o$$$$\n");
printw("$$$$$$o\"$$$o         oo$$$$$$$$$$$$$$$$$$$$\"o$$$$$\n");
printw("$$$$$$$$o\"$$$$ooooo$$$$$$$$$$$$$$$$$$$$$$\"o$$$$$$$\n");
printw("$$$$$$$$$$o\"\"$$$$$$$$$$$$$$$$$$$$$$$$$\"oo$$$$$$$$$\n");
printw("$$$$$$$$$$$$$o$\"\"$$$$$$$$$$$$$$$$$\"\"oo$$$$$$$$$$$$\n");
printw("$$$$$$$$$$$$$$$$$$o$o$\"$\"$\"$\"$oo$o$$$$$$$$$$$$$$$$\n");

refresh();
usleep(DELAY);
clear();
refresh();
usleep(DELAY);
clear();
 printw("$$$$$$$$$$$$$$$$\"\"$o$o$o$o$o$oo$$\"\"$$$$$$$$$$$$$$$\n");
printw("$$$$$$$$$$$$\"\"o$$$$$$$$$$\"$\"$$$$$$$o$\"$$$$$$$$$$$$\n");
printw("$$$$$$$$$\"$o$$$$\"\"$oo $ \"\"      \"\"\"$$$oo\"$$$$$$$$$\n");
printw("$$$$$$$\"o$$$$\"   \"\"o  $oo o o       \"\"$$$o\"$$$$$$$\n");
printw("$$$$$\"o$$$\"       oo$$$$$$$$$$o        \"$$$o\"$$$$$\n");
printw("$$$$\"o$$$  $  o$$$$$$$$$$$$$$\"$$oo       \"$$$ $$$$\n");
printw("$$$\"$$$\"   \"$$$$$$$$$$$$$$$$o$o$$$\"        $$$o$$$\n");
printw("$$ $$$    o$$$$$$$$$$$$$$$$$$$$$$$$o o   o  \"$$o\"$\n");
printw("$\"$$$\"    o$$$$$$$$$\"$$$$$$\"\" \"$$$$$$\"$$$$$  $$$\"$\n");
printw("$o$$\"    o$$$$$$$$$$o\"\"$$$\"\"\"\"ooo\"$$$$$$$$\"   $$$\"\n");
printw("$o$$\"    o$$$$$$$$$$            \"\"oo\"$\"$o\"\"   $$$o\n");
printw("o$$$     o$$$$$$$$$$                \"\"\"\"\"$    o$$o\n");
printw("o$$$    o$$$$$$$$$$$$o                   \"o \"oo$$o\n");
printw("o$$$  oo$$$$$$$$$$$$$$$$ooooooo$$$$$oo    $\"$ \"$$o\n");
printw("o$$$\"  \"\"  $$$$$$$$$$$$$$$$$$$$$$$$$$$$o    \" $$$\n");
printw("$ $$$       \"$$$$$$$$$$$$$$$$$$$$$$$$$$$o    o$$\"$\n");
printw("$$\"$$o       \"$$$$$$$$$$$$$$$$$$$$$$$$$$$o   $$$o$\n");
printw("$$o$$$o       $$\"\"$$$$$$$$$$$$$$$$$$$$$$$o  $$$ $$\n");
printw("$$$o\"$$o    \"$\"\"  \"$\"\"$$$$$$$$$$$$$$$$$$$oo$$$\"$$$\n");
printw("$$$$o\"$$$o        \"     $$$$$$$$$$$$$$$$$o$$\"o$$$$\n");
printw("$$$$$$o\"$$$o         oo$$$$$$$$$$$$$$$$$$$$\"o$$$$$\n");
printw("$$$$$$$$o\"$$$$ooooo$$$$$$$$$$$$$$$$$$$$$$\"o$$$$$$$\n");
printw("$$$$$$$$$$o\"\"$$$$$$$$$$$$$$$$$$$$$$$$$\"oo$$$$$$$$$\n");
printw("$$$$$$$$$$$$$o$\"\"$$$$$$$$$$$$$$$$$\"\"oo$$$$$$$$$$$$\n");
printw("$$$$$$$$$$$$$$$$$$o$o$\"$\"$\"$\"$oo$o$$$$$$$$$$$$$$$$\n");
 
printw("\nenter anything to continue\n");
}

void printstory(){
clear();
	printw("long time ago........\n");
}
void printName(){
clear();
printw("  \n");
printw("  \n");
printw("  \n");
printw("  \n");
printw(" )\n");
printw("(_\n");
printw("  \n");
printw("  \n");
printw("  \n");
printw("  \n");
printw(" /\n");
printw("(_\n");
refresh();
usleep(DELAY);
clear();
printw("    \n");
printw("   (\n");
printw("    \n");
printw("    \n");
printw(" ) /\n");
printw("(_/ \n");
printw("    \n");
printw("    \n");
printw("    \n");
printw("   _\n");
printw(" /  \n");
printw("(__ \n");
refresh();
usleep(DELAY);
clear();
printw("    __\n");
printw("   (, \n");
printw("    _/\n");
printw("    / \n");
printw(" ) /  \n");
printw("(_/   \n");
printw("      \n");
printw("     (\n");
printw("      \n");
printw("   ___\n");
printw(" /   /\n");
printw("(__ / \n");
refresh();
usleep(DELAY);
clear();
printw("    ____\n");
printw("   (, / \n");
printw("    _/__\n");
printw("    /   \n");
printw(" ) /    \n");
printw("(_/     \n");
printw("      __\n");
printw("     (, \n");
printw("       /\n");
printw("   ___/_\n");
printw(" /   /  \n");
printw("(__ /   \n");
refresh();
usleep(DELAY);
clear();
printw("    _____ \n");
printw("   (, /   \n");
printw("    _/__ /\n");
printw("    /     \n");
printw(" ) /      \n");
printw("(_/       \n");
printw("      ____\n");
printw("     (, / \n");
printw("       /  \n");
printw("   ___/___\n");
printw(" /   /    \n");
printw("(__ /     \n");
refresh();
usleep(DELAY);
clear();
printw("    _____   \n");
printw("   (, /   ) \n");
printw("    _/__ / _\n");
printw("    /     / \n");
printw(" ) /        \n");
printw("(_/         \n");
printw("      _____ \n");
printw("     (, /  ,\n");
printw("       /    \n");
printw("   ___/___(_\n");
printw(" /   /      \n");
printw("(__ /       \n");
refresh();
usleep(DELAY);
clear();
printw("    _____     \n");
printw("   (, /   )   \n");
printw("    _/__ / __ \n");
printw("    /     / (_\n");
printw(" ) /          \n");
printw("(_/           \n");
printw("      _____   \n");
printw("     (, /  ,  \n");
printw("       /    __\n");
printw("   ___/___(_/ \n");
printw(" /   /        \n");
printw("(__ /         \n");
refresh();
usleep(DELAY);
clear();
printw("    _____       \n");
printw("   (, /   )     \n");
printw("    _/__ / __   \n");
printw("    /     / (__(\n");
printw(" ) /            \n");
printw("(_/             \n");
printw("      _____     \n");
printw("     (, /  ,    \n");
printw("       /    __  \n");
printw("   ___/___(_/ (_\n");
printw(" /   /         .\n");
printw("(__ /         (_\n");
refresh();
usleep(DELAY);
clear();
printw("    _____         \n");
printw("   (, /   )       \n");
printw("    _/__ / __   _ \n");
printw("    /     / (__(/_\n");
printw(" ) /              \n");
printw("(_/               \n");
printw("      _____       \n");
printw("     (, /  ,      \n");
printw("       /    __   _\n");
printw("   ___/___(_/ (_(_\n");
printw(" /   /         .-/\n");
printw("(__ /         (_/ \n");
refresh();
usleep(DELAY);
clear();
printw("    _____           \n");
printw("   (, /   )         \n");
printw("    _/__ / __   _  _\n");
printw("    /     / (__(/_/_\n");
printw(" ) /                \n");
printw("(_/                 \n");
printw("      _____         \n");
printw("     (, /  ,        \n");
printw("       /    __   _  \n");
printw("   ___/___(_/ (_(_/_\n");
printw(" /   /         .-/  \n");
printw("(__ /         (_/   \n");
refresh();
usleep(DELAY);
clear();
printw("    _____             \n");
printw("   (, /   )           \n");
printw("    _/__ / __   _  _  \n");
printw("    /     / (__(/_/_)_\n");
printw(" ) /                  \n");
printw("(_/                   \n");
printw("      _____           \n");
printw("     (, /  ,          \n");
printw("       /    __   _    \n");
printw("   ___/___(_/ (_(_/_  \n");
printw(" /   /         .-/    \n");
printw("(__ /         (_/     \n");
refresh();
usleep(DELAY);
clear();
printw("    _____               \n");
printw("   (, /   )             \n");
printw("    _/__ / __   _  _    \n");
printw("    /     / (__(/_/_)__(\n");
printw(" ) /                    \n");
printw("(_/                     \n");
printw("      _____             \n");
printw("     (, /  ,            \n");
printw("       /    __   _     _\n");
printw("   ___/___(_/ (_(_/_  (_\n");
printw(" /   /         .-/      \n");
printw("(__ /         (_/       \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                  \n");
printw("   (, /   )                \n");
printw("    _/__ / __   _  _    _ _\n");
printw("    /     / (__(/_/_)__(/_/\n");
printw(" ) /                       \n");
printw("(_/                        \n");
printw("      _____                \n");
printw("     (, /  ,               \n");
printw("       /    __   _     _  _\n");
printw("   ___/___(_/ (_(_/_  (_(_/\n");
printw(" /   /         .-/         \n");
printw("(__ /         (_/          \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                    \n");
printw("   (, /   )                  \n");
printw("    _/__ / __   _  _    _ __ \n");
printw("    /     / (__(/_/_)__(/_/ (\n");
printw(" ) /                         \n");
printw("(_/                          \n");
printw("      _____                  \n");
printw("     (, /  ,                 \n");
printw("       /    __   _     _  __ \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (\n");
printw(" /   /         .-/           \n");
printw("(__ /         (_/            \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                      \n");
printw("   (, /   )                    \n");
printw("    _/__ / __   _  _    _ __  _\n");
printw("    /     / (__(/_/_)__(/_/ (_(\n");
printw(" ) /                           \n");
printw("(_/                            \n");
printw("      _____                    \n");
printw("     (, /  ,                   \n");
printw("       /    __   _     _  __   \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(\n");
printw(" /   /         .-/             \n");
printw("(__ /         (_/              \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                        \n");
printw("   (, /   )                      \n");
printw("    _/__ / __   _  _    _ __  _/_\n");
printw("    /     / (__(/_/_)__(/_/ (_(__\n");
printw(" ) /                             \n");
printw("(_/                              \n");
printw("      _____                      \n");
printw("     (, /  ,                     /\n");
printw("       /    __   _     _  __   _(/\n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_\n");
printw(" /   /         .-/                \n");
printw("(__ /         (_/                 \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                          \n");
printw("   (, /   )                        \n");
printw("    _/__ / __   _  _    _ __  _/_  \n");
printw("    /     / (__(/_/_)__(/_/ (_(___(\n");
printw(" ) /                               \n");
printw("(_/                                \n");
printw("      _____                          \n");
printw("     (, /  ,                     /)  \n");
printw("       /    __   _     _  __   _(/   \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_   \n");
printw(" /   /         .-/                   \n");
printw("(__ /         (_/                    \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                            \n");
printw("   (, /   )                          \n");
printw("    _/__ / __   _  _    _ __  _/_  _ \n");
printw("    /     / (__(/_/_)__(/_/ (_(___(/_\n");
printw(" ) /                                 \n");
printw("(_/                                  \n");
printw("      _____                            _\n");
printw("     (, /  ,                     /)   (,\n");
printw("       /    __   _     _  __   _(/      \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_     (\n");
printw(" /   /         .-/                    ) \n");
printw("(__ /         (_/                    (__\n");
refresh();
usleep(DELAY);
clear();
printw("    _____                               \n");
printw("   (, /   )                             \n");
printw("    _/__ / __   _  _    _ __  _/_  _  _(\n");
printw("    /     / (__(/_/_)__(/_/ (_(___(/_(_(\n");
printw(" ) /                                    \n");
printw("(_/                                     \n");
printw("      _____                            __  \n");
printw("     (, /  ,                     /)   (, ) \n");
printw("       /    __   _     _  __   _(/      /  \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_     (___\n");
printw(" /   /         .-/                    )   /\n");
printw("(__ /         (_/                    (__ / \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                                  \n");
printw("   (, /   )                             /) \n");
printw("    _/__ / __   _  _    _ __  _/_  _  _(/  \n");
printw("    /     / (__(/_/_)__(/_/ (_(___(/_(_(_  \n");
printw(" ) /                                       \n");
printw("(_/                                        \n");
printw("      _____                            __     \n");
printw("     (, /  ,                     /)   (, )   /\n");
printw("       /    __   _     _  __   _(/      /   / \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_     (___/_ \n");
printw(" /   /         .-/                    )   /   \n");
printw("(__ /         (_/                    (__ /    \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                                    \n");
printw("   (, /   )                             /)   \n");
printw("    _/__ / __   _  _    _ __  _/_  _  _(/   (\n");
printw("    /     / (__(/_/_)__(/_/ (_(___(/_(_(_  /_\n");
printw(" ) /                                         \n");
printw("(_/                                          \n");
printw("      _____                            __     __)\n");
printw("     (, /  ,                     /)   (, )   /   \n");
printw("       /    __   _     _  __   _(/      /   /    \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_     (___/_ (_(\n");
printw(" /   /         .-/                    )   /      \n");
printw("(__ /         (_/                    (__ /       \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                                       \n");
printw("   (, /   )                             /)   /) \n");
printw("    _/__ / __   _  _    _ __  _/_  _  _(/   (/_ \n");
printw("    /     / (__(/_/_)__(/_/ (_(___(/_(_(_  /_) (\n");
printw(" ) /                                          .-\n");
printw("(_/                                          (_/\n");
printw("      _____                            __     __)  \n");
printw("     (, /  ,                     /)   (, )   /     \n");
printw("       /    __   _     _  __   _(/      /   /      \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_     (___/_ (_(__\n");
printw(" /   /         .-/                    )   /        \n");
printw("(__ /         (_/                    (__ /         \n");
refresh();
usleep(DELAY);
clear();
printw("    _____                                          \n");
printw("   (, /   )                             /)   /)    \n");
printw("    _/__ / __   _  _    _ __  _/_  _  _(/   (/_    \n");
printw("    /     / (__(/_/_)__(/_/ (_(___(/_(_(_  /_) (_/_\n");
printw(" ) /                                          .-/  \n");
printw("(_/                                          (_/   \n");
printw("      _____                            __     __)     \n");
printw("     (, /  ,                     /)   (, )   /        \n");
printw("       /    __   _     _  __   _(/      /   /       _ \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_     (___/_ (_(__(/_\n");
printw(" /   /         .-/                    )   /           \n");
printw("(__ /         (_/                    (__ /            \n");
refresh();
usleep(DELAY);
clear();
refresh();
usleep(DELAY);
clear();
printw("    _____                                          \n");
printw("   (, /   )                             /)   /)    \n");
printw("    _/__ / __   _  _    _ __  _/_  _  _(/   (/_    \n");
printw("    /     / (__(/_/_)__(/_/ (_(___(/_(_(_  /_) (_/_\n");
printw(" ) /                                          .-/  \n");
printw("(_/                                          (_/   \n");
printw("      _____                            __     __)     \n");
printw("     (, /  ,                     /)   (, )   /        \n");
printw("       /    __   _     _  __   _(/      /   /       _ \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_     (___/_ (_(__(/_\n");
printw(" /   /         .-/                    )   /           \n");
printw("(__ /         (_/                    (__ /            \n");
refresh();
usleep(DELAY);
clear();
refresh();
usleep(DELAY);
clear();
printw("    _____                                          \n");
printw("   (, /   )                             /)   /)    \n");
printw("    _/__ / __   _  _    _ __  _/_  _  _(/   (/_    \n");
printw("    /     / (__(/_/_)__(/_/ (_(___(/_(_(_  /_) (_/_\n");
printw(" ) /                                          .-/  \n");
printw("(_/                                          (_/   \n");
printw("      _____                            __     __)     \n");
printw("     (, /  ,                     /)   (, )   /        \n");
printw("       /    __   _     _  __   _(/      /   /       _ \n");
printw("   ___/___(_/ (_(_/_  (_(_/ (_(_(_     (___/_ (_(__(/_\n");
printw(" /   /         .-/                    )   /           \n");
printw("(__ /         (_/                    (__ /            \n");
printw("\nenter anything to continue\n");
}
void printOptions(){
clear();
printw("_____________________________________\n");
printw("|Options                            |\n");
printw("|? :list all options and command    |\n");
printw("|w,s,a,d :Control directions(attack)|\n");
printw("|i: list inventory                  |\n");
printw("|u: use item                        |\n");
printw("|o: sell item                       |\n");
printw("|p: buy item                        |\n");
printw("|[: drop item                       |\n");
printw("|]: list skill                      |\n");
printw("|o: sell item                       |\n");
printw("|j: use racial skills               |\n");
printw("|k: use class skill 1               |\n");
printw("|l: use class skill 2               |\n");
printw("|;: use ultimate skill              |\n");
printw("|r: restart game                    |\n");
printw("|q: quit game                       |\n");
printw("|___________________________________|\n");
printw("\nenter anything to continue\n");
char c;
c=getch();
clear();
}
void printClassOption(){
clear();
printw("Congratulations, you are power enough to choose a class\n");
printw("M:Mage______Mages demolish their foes with arcane incantations. Although they wield powerful offensive spells, mages are fragile and lightly armored\n");
printw("            Skills:Frost Nova, Fire Blast\n");
printw("            Advanced class:Spirit Healer, Blood Mage\n\n");
printw("W:Warrior______Warriors equip themselves carefully for combat and engage their enemies head-on, letting attacks glance off their heavy armor.\n");
printw("              Skills:Whirlwind, Demoralizing Shout\n");
printw("              Advanced class:Ranger , Berserker\n\n");
printw("K:Knight______Knight stand directly in front of their enemies, relying on heavy armor and healing in order to survive incoming attacks\n");
printw("              Skills:Slam, Spiritual Healing\n");
printw("              Advanced class:Death Knight , Paladin\n");
       
}
void printGameOver(){
printw("                                   .::!!!!!!!:.\n");
printw("  .!!!!!:.                        .:!!!!!!!!!!!!\n");
printw("  ~~~~!!!!!!.                 .:!!!!!!!!!UWWW$$$ \n");
printw("      :$$NWX!!:           .:!!!!!!XUWW$$$$$$$$$P \n");
printw("      $$$$$##WX!:      .<!!!!UW$$$$\"  $$$$$$$$# \n");
printw("      $$$$$  $$$UX   :!!UW$$$$$$$$$   4$$$$$* \n");
printw("      ^$$$B  $$$$\\     $$$$$$$$$$$$   d$$R\" \n");
printw("        \"*$bd$$$$      \'*$$$$$$$$$$$o+#\" \n");
printw("             \"\"\"\"          \"\"\"\"\"\"\" \n");
printw("  ____    _    __  __ _____    _____     _______ ____  \n");
printw(" / ___|  / \\  |  \\/  | ____|  / _ \\ \\   / / ____|  _ \\ \n");
printw("| |  _  / _ \\ | |\\/| |  _|   | | | \\ \\ / /|  _| | |_) |\n");
printw("| |_| |/ ___ \\| |  | | |___  | |_| |\\ V / | |___|  _ < \n");
printw(" \\____/_/   \\_\\_|  |_|_____|  \\___/  \\_/  |_____|_| \\_\\\n\n");
printw("q: Quit\n");
printw("r: Restart\n");                                                      
}

void printWon(){
printw("------------------------------------------------------\n");
printw("m     m  mmmm  m    m       m     m  mmmm  mm   m\n");
printw(" \"m m\"  m\"  \"m #    #       #  #  # m\"  \"m #\"m  #\n");
printw("  \"#\"   #    # #    #       \" #\"# # #    # # #m #\n");
printw("   #    #    # #    #        ## ##\" #    # #  # #\n");
printw("   #     #mm#  \"mmmm\"        #   #   #mm#  #   ##\n");
printw("------------------------------------------------------\n");
printw("      \\                    / \\  //\\\n");
printw("       \\    |\\___/|      /   \\//  \\\\\n");
printw("            /0  0  \\__  /    //  | \\ \\    \n");
printw("           /     /  \\/_/    //   |  \\  \\  \n");
printw("           @_^_@'/   \\/_   //    |   \\   \\ \n");
printw("           //_^_/     \\/_ //     |    \\    \\\n");
printw("        ( //) |        \\///      |     \\     \\\n");
printw("      ( / /) _|_ /   )  //       |      \\     _\\\n");
printw("    ( // /) '/,_ _ _/  ( ; -.    |    _ _\\.-~        .-~~~^-.\n");
printw("  (( / / )) ,-{        _      `-.|.-~-.           .~         `.\n");
printw(" (( // / ))  '/\\      /                 ~-. _ .-~      .-~^-.  \\\n");
printw(" (( /// ))      `.   {            }                   /      \\  \\\n");
printw("  (( / ))     .----~-.\\        \\-'                 .~         \\  `. \\^-.\n");
printw("             ///.----..>        \\             _ -~             `.  ^-`  ^-_\n");
printw("               ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~\n");
printw("                                                                  /.-~\n");
                                                                  
}

